/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.31.6.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./HackCw20.types";
import * as _1 from "./HackCw20.client";
import * as _2 from "./HackCw20.provider";
import * as _3 from "./Counter.types";
import * as _4 from "./Counter.client";
import * as _5 from "./Counter.provider";
import * as _6 from "./NeutronShield.types";
import * as _7 from "./NeutronShield.client";
import * as _8 from "./NeutronShield.provider";
export namespace contracts {
  export const HackCw20 = { ..._0,
    ..._1,
    ..._2
  };
  export const Counter = { ..._3,
    ..._4,
    ..._5
  };
  export const NeutronShield = { ..._6,
    ..._7,
    ..._8
  };
}